name: payverve
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_svg: 2.0.6
  fl_chart: 0.62.0
  scroll_snap_list: 0.9.1
  firebase_core: 2.13.1
  flutter_native_splash: 2.3.1
  image_picker: 0.8.7+5
  cloud_firestore: 4.8.0
  hive_flutter: 1.1.0
  hive: 2.2.3
  intl: 0.18.1
  firebase_storage: 11.2.2
  encrypt: 5.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/json/
  uses-material-design: true

